# Generated by Django 4.2.1 on 2023-08-01 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backendcore', '0002_alter_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='datedue',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
